### ISSUE TITLE
database.ymlの記述について

### ISSUE THREAD

**Issue by suzuki-mar** [Aryota/Task#1]
## パスワードをENVで試せるようにしたほうがいいと思います
Defaultのパスワードは他のWebサービスでも使用しているものでしょうか?
もしそうであるなら、パスワードが流失する可能性があるので他のパスワードにするか
ENVで指定できるようにしたほうがいいと思います
パスワード等の情報を書くときは ENVが使えないかを考えてみたほうがいいと思います

## データベースの情報はアンダースコア形式にするのが一般的です
* Database名はアンダースコア形式にするのが一般的です
* Usernameはアンダースコア形式にするのが一般的です

理由は調べてみてください

**Comment by Aryota** [comment]
パスワードをENVで管理に変更しました。
アンダースコアは大文字と小文字の区別がないからということですかね。
